name: Code Quality

on: [ pull_request ]

jobs:

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.14.0'
      - name: Run Eslint Check
        run: |
          cd frontend
          rm -rf node_modules
          npm install
          npm install eslint-plugin-prettier --save-dev
          npm install eslint-config-prettier
          npm run lint
       
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend
      - name: Run Prettier
        run: npx prettier --check .
        working-directory: ./frontend

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build with Maven
        run: |
          cd backend
          mvn checkstyle:check

  pmd:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Run PMD Scan
        run: |
          cd backend
          mvn install
          mvn pmd:check

  spotless:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Run Spotless check
        run: |
          cd backend
          mvn -version
          mvn install -DskipTests
          mvn spotless:check

  owasp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Run OWASP Dependency-Check
        run: |
          cd backend
          mvn install -DskipTests
          mvn dependency-check:check

  jacoco:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Run JaCoCo
        run: |
          cd backend
          mvn clean test